/*
 Navicat Premium Data Transfer

 Source Server         : cleanCode
 Source Server Type    : PostgreSQL
 Source Server Version : 130001
 Source Host           : localhost:5432
 Source Catalog        : postgres
 Source Schema         : common16

 Target Server Type    : PostgreSQL
 Target Server Version : 130001
 File Encoding         : 65001

 Date: 04/02/2021 10:49:01
*/


-- ----------------------------
-- Sequence structure for course_course_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "common16"."course_course_id_seq";
CREATE SEQUENCE "common16"."course_course_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for hibernate_sequence
-- ----------------------------
DROP SEQUENCE IF EXISTS "common16"."hibernate_sequence";
CREATE SEQUENCE "common16"."hibernate_sequence" 
INCREMENT 1
MINVALUE  1
MAXVALUE 9223372036854775807
START 1
CACHE 1;

-- ----------------------------
-- Table structure for course
-- ----------------------------
DROP TABLE IF EXISTS "common16"."course";
CREATE TABLE "common16"."course" (
  "course_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "course_name" varchar(255) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "location" varchar(255) COLLATE "pg_catalog"."default",
  "opened" timestamp(6),
  "teacher_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for enrolls
-- ----------------------------
DROP TABLE IF EXISTS "common16"."enrolls";
CREATE TABLE "common16"."enrolls" (
  "enroll_id" int4 NOT NULL,
  "course_id" int4 NOT NULL,
  "student_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for student
-- ----------------------------
DROP TABLE IF EXISTS "common16"."student";
CREATE TABLE "common16"."student" (
  "year" int4,
  "student_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for teacher
-- ----------------------------
DROP TABLE IF EXISTS "common16"."teacher";
CREATE TABLE "common16"."teacher" (
  "experiences" int4,
  "phone" varchar(255) COLLATE "pg_catalog"."default",
  "teacher_id" int4 NOT NULL
)
;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS "common16"."user";
CREATE TABLE "common16"."user" (
  "user_id" int4 NOT NULL,
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "user_name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "common16"."course_course_id_seq"
OWNED BY "common16"."course"."course_id";
SELECT setval('"common16"."course_course_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
SELECT setval('"common16"."hibernate_sequence"', 7, true);

-- ----------------------------
-- Primary Key structure for table course
-- ----------------------------
ALTER TABLE "common16"."course" ADD CONSTRAINT "course_pkey" PRIMARY KEY ("course_id");

-- ----------------------------
-- Primary Key structure for table enrolls
-- ----------------------------
ALTER TABLE "common16"."enrolls" ADD CONSTRAINT "enrolls_pkey" PRIMARY KEY ("enroll_id");

-- ----------------------------
-- Primary Key structure for table student
-- ----------------------------
ALTER TABLE "common16"."student" ADD CONSTRAINT "student_pkey" PRIMARY KEY ("student_id");

-- ----------------------------
-- Primary Key structure for table teacher
-- ----------------------------
ALTER TABLE "common16"."teacher" ADD CONSTRAINT "teacher_pkey" PRIMARY KEY ("teacher_id");

-- ----------------------------
-- Primary Key structure for table user
-- ----------------------------
ALTER TABLE "common16"."user" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("user_id");

-- ----------------------------
-- Foreign Keys structure for table course
-- ----------------------------
ALTER TABLE "common16"."course" ADD CONSTRAINT "fksybhlxoejr4j3teomm5u2bx1n" FOREIGN KEY ("teacher_id") REFERENCES "common16"."teacher" ("teacher_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table enrolls
-- ----------------------------
ALTER TABLE "common16"."enrolls" ADD CONSTRAINT "fk286jfovh1kgqtntwaxor1mxq8" FOREIGN KEY ("student_id") REFERENCES "common16"."student" ("student_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "common16"."enrolls" ADD CONSTRAINT "fkq5rdjekyv4jh54uf8y7wo8dcs" FOREIGN KEY ("course_id") REFERENCES "common16"."course" ("course_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table student
-- ----------------------------
ALTER TABLE "common16"."student" ADD CONSTRAINT "fkmlyxb44mx4v92t1eq5v655fk3" FOREIGN KEY ("student_id") REFERENCES "common16"."user" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ----------------------------
-- Foreign Keys structure for table teacher
-- ----------------------------
ALTER TABLE "common16"."teacher" ADD CONSTRAINT "fk95g4kwoji012jrf9u2a5rmvxp" FOREIGN KEY ("teacher_id") REFERENCES "common16"."user" ("user_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
