/*
 Navicat Premium Data Transfer

 Source Server         : cleanCode
 Source Server Type    : PostgreSQL
 Source Server Version : 130001
 Source Host           : localhost:5432
 Source Catalog        : postgres
 Source Schema         : common16

 Target Server Type    : PostgreSQL
 Target Server Version : 130001
 File Encoding         : 65001

 Date: 02/02/2021 14:47:19
*/


-- ----------------------------
-- Sequence structure for course_course_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "common16"."course_course_id_seq";
CREATE SEQUENCE "common16"."course_course_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for student_student_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "common16"."student_student_id_seq";
CREATE SEQUENCE "common16"."student_student_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for teacher_teacher_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "common16"."teacher_teacher_id_seq";
CREATE SEQUENCE "common16"."teacher_teacher_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Sequence structure for user_user_id_seq
-- ----------------------------
DROP SEQUENCE IF EXISTS "common16"."user_user_id_seq";
CREATE SEQUENCE "common16"."user_user_id_seq" 
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
CACHE 1;

-- ----------------------------
-- Table structure for course
-- ----------------------------
DROP TABLE IF EXISTS "common16"."course";
CREATE TABLE "common16"."course" (
  "course_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "course_name" varchar(255) COLLATE "pg_catalog"."default",
  "description" varchar(255) COLLATE "pg_catalog"."default",
  "opened" timestamp(6),
  "teacher_id" int4,
  "location" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for enroll
-- ----------------------------
DROP TABLE IF EXISTS "common16"."enroll";
CREATE TABLE "common16"."enroll" (
  "student_id" int4,
  "course_id" int4
)
;

-- ----------------------------
-- Table structure for student
-- ----------------------------
DROP TABLE IF EXISTS "common16"."student";
CREATE TABLE "common16"."student" (
  "student_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "user_id" int4,
  "year" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Table structure for teacher
-- ----------------------------
DROP TABLE IF EXISTS "common16"."teacher";
CREATE TABLE "common16"."teacher" (
  "teacher_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "experiences" int4,
  "phone" varchar(255) COLLATE "pg_catalog"."default",
  "user_id" int4
)
;

-- ----------------------------
-- Table structure for user
-- ----------------------------
DROP TABLE IF EXISTS "common16"."user";
CREATE TABLE "common16"."user" (
  "user_id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (
INCREMENT 1
MINVALUE  1
MAXVALUE 2147483647
START 1
),
  "email" varchar(255) COLLATE "pg_catalog"."default",
  "password" varchar(255) COLLATE "pg_catalog"."default",
  "user_name" varchar(255) COLLATE "pg_catalog"."default"
)
;

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "common16"."course_course_id_seq"
OWNED BY "common16"."course"."course_id";
SELECT setval('"common16"."course_course_id_seq"', 2, false);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "common16"."student_student_id_seq"
OWNED BY "common16"."student"."student_id";
SELECT setval('"common16"."student_student_id_seq"', 4, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "common16"."teacher_teacher_id_seq"
OWNED BY "common16"."teacher"."teacher_id";
SELECT setval('"common16"."teacher_teacher_id_seq"', 5, true);

-- ----------------------------
-- Alter sequences owned by
-- ----------------------------
ALTER SEQUENCE "common16"."user_user_id_seq"
OWNED BY "common16"."user"."user_id";
SELECT setval('"common16"."user_user_id_seq"', 13, true);

-- ----------------------------
-- Primary Key structure for table course
-- ----------------------------
ALTER TABLE "common16"."course" ADD CONSTRAINT "course_pkey" PRIMARY KEY ("course_id");

-- ----------------------------
-- Primary Key structure for table student
-- ----------------------------
ALTER TABLE "common16"."student" ADD CONSTRAINT "student_pkey" PRIMARY KEY ("student_id");

-- ----------------------------
-- Primary Key structure for table teacher
-- ----------------------------
ALTER TABLE "common16"."teacher" ADD CONSTRAINT "teacher_pkey" PRIMARY KEY ("teacher_id");

-- ----------------------------
-- Primary Key structure for table user
-- ----------------------------
ALTER TABLE "common16"."user" ADD CONSTRAINT "user_pkey" PRIMARY KEY ("user_id");

-- ----------------------------
-- Foreign Keys structure for table enroll
-- ----------------------------
ALTER TABLE "common16"."enroll" ADD CONSTRAINT "enroll_course_id_fkey" FOREIGN KEY ("course_id") REFERENCES "common16"."course" ("course_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "common16"."enroll" ADD CONSTRAINT "enroll_student_id_fkey" FOREIGN KEY ("student_id") REFERENCES "common16"."student" ("student_id") ON DELETE NO ACTION ON UPDATE NO ACTION;
